apiVersion: v1
kind: Service
metadata: 
  name: dubbo-consumer-service
spec:
  type: ClusterIP
  selector:
    app: dubbo-consumer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: dubbo-consumer-service-port
  clusterIP: None

