apiVersion: v1
kind: Service
metadata: 
  name: dubbo-provider-service
spec:
  selector:
    app: dubbo-provider
  type: NodePort
  ports:
  - protocol: TCP
    port: 30000
    nodePort: 30000
    targetPort: 30000
    name: dubbo-provider-service-port
